export const SERVICES = [
  {
    id: 'deep-clean',
    title: 'Deep Clean',
    benefit: 'Your vehicle, transformed inside and out. Our entry-level package is a comprehensive deep clean of both interior and exterior — every surface meticulously restored to a like-new, factory-fresh finish. Includes the engine bay.',
    description: 'Full interior & exterior detail including engine bay. Qualifies you for 6 months of regular maintenance cleans every 3–8 weeks.',
    price: 'From £160',
    duration: '5–6 Hours',
    image: '/DEEP CLEAN 🚨We had this beautiful bmw 535d in for a deep cleanWe manage to reset the leather se.jpg',
  },
  {
    id: 'protect',
    title: 'Protect',
    benefit: 'Industry-leading vehicle protection designed to preserve your car\'s value, enhance its appearance, and keep it looking cleaner for longer. Exceptional gloss, outstanding water repellency, and superior resistance to environmental contaminants.',
    description: 'Intensive decontamination + 12-month ceramic coating. Includes engine bay & interior. Upgrade to 24-month coating for just £80 extra. Qualifies for 12 months of maintenance.',
    price: 'From £250',
    duration: '6–7 Hours',
    image: '/hero section/can_you_edit_this_image_202605151336.jpeg',
  },
  {
    id: 'enhance',
    title: 'Enhance',
    benefit: 'Precision machine polishing eliminates defects — swirl marks, light scratches, water etchings. Your exterior finish is restored to its absolute peak before a 24-month protective coating locks in that perfection.',
    description: 'Paint correction via machine polishing + 24-month ceramic coating. Qualifies for 24 months of regular maintenance.',
    price: 'From £380',
    duration: '1–1.5 Days',
    image: '/gallaryimg2.jpg',
    objectPosition: 'bottom',
  },
  {
    id: 'maintenance',
    title: 'Maintenance Clean',
    benefit: 'Keep your investment protected. Our maintenance clean is designed for clients who want to preserve and extend the results of their initial package — scheduled every 3 to 6 weeks to keep your car in showroom condition.',
    description: 'Available after Deep Clean (up to 6 months), Protect (12–24 months), or Enhance (24 months). Regular scheduling keeps your protection performing at its best.',
    price: 'From £90',
    duration: '3–4 Hours',
    image: '/hero section/can_you_edit_this_image_202605151336 (1).jpeg',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Katrin Ivanova',
    car: 'Deep Clean',
    text: 'I cannot recommend Philip enough! Excellent service, extremely professional, passionate and my car was cleaned to a very high standard. I had a little mark on the back seat which he cleaned for me even though cleaning the seats was not included in my package. I\'ve also received a little spray gift which smells amazing. Thank you so much again for cleaning my car so well.',
    stars: 5,
  },
  {
    name: 'David',
    car: 'Red Sports Car',
    text: 'Just had Phil out for my car, wow what a transformation! My car is my pride and joy and was in very much need of some tlc. Used Phil for first time after switching valeter what a difference. Attention to detail is faultless and the time is taken to get the ultimate new car again finish. Will highly recommend and be using his service again and again.',
    stars: 5,
  },
  {
    name: 'Victoria',
    car: 'Full Detail',
    text: 'After recommendations on Facebook, I contacted King of Detailing, to clean my daughters car. The communication was excellent. Everything clear and easy to book. Philip arrived today for our appointment, on time and got to work straight away. Was a excellent job and very efficient. The car was spotless and smelt so clean. The carpets/mats were like brand new again. Highly recommend and will definitely be using him again.',
    stars: 5,
  },
];

export const ACCREDITATIONS = [
  { name: 'Fully Insured', logo: '' },
  { name: 'Fully Mobile', logo: '' },
];

export const COMPANY_DETAILS = {
  name: 'King of Detailing',
  tagline: 'Premium Car Care · Luton & Bedfordshire',
  address: 'Delivering Automotive Perfection Across Luton, Herts, Beds & Bucks',
  travelRange: 'Happy to travel 1 hour driving distance',
  phone: '07725 727 176',
  phoneRaw: '07725727176',
  hours: 'Mon – Sun  8:00 AM – 8:00 PM',
  bookingUrl: 'https://wa.me/447725727176',
  whatsapp: 'https://wa.me/447725727176',
  instagram: 'https://www.instagram.com/king.ofdetailing/',
  facebook: 'https://www.facebook.com/profile.php?id=61575679937406',
  websiteUrl: 'https://www.kingofdetailinguk.com/',
};

export const GALLERY_MEDIA = [
  {
    id: 1,
    type: "video",
    title: "Showcase in Motion",
    desc: "Experience the King of Detailing standard in every frame.",
    url: "/gallaryvideo1.mp4",
    span: "md:col-span-2 md:row-span-2 sm:col-span-2 sm:row-span-2",
  },
  {
    id: 2,
    type: "image",
    title: "M-Power Transformation",
    desc: "A comprehensive reset for this beautiful BMW 535d.",
    url: "/DEEP CLEAN 🚨We had this beautiful bmw 535d in for a deep cleanWe manage to reset the leather se (1).jpg",
    span: "md:col-span-1 md:row-span-3 sm:col-span-2 sm:row-span-2",
  },
  {
    id: 3,
    type: "image",
    title: "Signature Gloss",
    desc: "Flawless reflection and ultimate clarity on every surface.",
    url: "/gallaryimg1.webp",
    span: "md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 4,
    type: "image",
    title: "Ceramic Shield",
    desc: "Advanced protection for a long-lasting, showroom finish.",
    url: "/gallaryimg2.jpg",
    span: "md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 5,
    type: "image",
    title: "Ultimate Protection",
    desc: "Extreme water beading and superior environmental resistance.",
    url: "/gallaryimg3.jpg",
    span: "md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 6,
    type: "image",
    title: "Trusted Choice",
    desc: "Pushing the boundaries of automotive care every single day.",
    url: "/hero section/can_you_edit_this_image_202605151336.jpeg",
    span: "md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 7,
    type: "image",
    title: "Showroom Shine",
    desc: "Precision polishing to remove defects and maximize depth.",
    url: "/SnapInsta.to_515583121_17851126407484826_2354586917554232743_n.jpg",
    span: "md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 8,
    type: "image",
    title: "Reflection Perfection",
    desc: "Mirror-like finish achieved through meticulous correction.",
    url: "/SnapInsta.to_529623079_17855051943484826_20614504980163342_n_1080.jpg",
    span: "md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 9,
    type: "image",
    title: "Legendary Service",
    desc: "Honored to detail Bernie Fineman's vehicle to our highest standard.",
    url: "/Today we carried out our deep clean package for no other then the legendary Bernie fineman!Berni (1).jpg",
    span: "md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2",
  },
  {
    id: 10,
    type: "image",
    title: "Signature Maintenance",
    desc: "Preserving that showroom finish with regular, professional care.",
    url: "/hero section/can_you_edit_this_image_202605151336 (1).jpeg",
    span: "md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2",
  },
];
