export const SERVICES = [
  {
    id: 'maintenance',
    title: 'Maintenance Plan',
    badge: 'Best Value',
    subtitle: 'Regular upkeep, scheduled every 2–4 weeks',
    benefit: 'Keep your protection layer topped up and your car consistently sharp — without lifting a finger.',
    description: [
      'Pre-wash / rinse / snow foam',
      'Wheel arches deep clean',
      'Wheels & tyres cleaned',
      'Safe wash (2-bucket method)',
      'Interior vacuum',
      'Interior & exterior glass cleaned',
      'Interior seats wiped',
      'Spray sealant (3 months protection)',
      'Tyre dressing',
      'Air freshener',
    ],
    price: 'From £50',
    duration: '1.5–2 hrs',
    image: '/793160120_2237154940475605_1833440236133772156_n.jpg',
    bookingUrl: 'https://wa.me/447393682365?text=Hi%20Rhys%2C%20I%20would%20like%20to%20book%20a%20Maintenance%20Plan%20car%20model%20%3A%20',
  },
  {
    id: 'full-valet',
    title: 'Full Valet Package',
    badge: 'Most Popular',
    subtitle: 'The comprehensive reset your car deserves',
    benefit: 'A ground-up reset that turns an everyday car into something that makes every journey feel like the first one.',
    description: [
      'Pre-wash / rinse / snow foam',
      'Safe wash (3-bucket method)',
      'Drying towel finish',
      'Door shuts cleaned',
      'Interior vacuum',
      'Steamed seats or leather cleaned',
      'Carpets shampooed',
      'All trims & headlining cleaned',
      'Tyres & bodywork trim dressed',
      'Interior & exterior glass cleaned',
      'Tar removed',
      'Spray sealant (4 months protection)',
      'Air freshener',
    ],
    price: 'From £70',
    duration: '3–4 hrs',
    image: '/724893959_1438592524987609_4973891884401838852_n.jpg',
    objectPosition: 'center bottom',
    bookingUrl: 'https://wa.me/447393682365?text=Hi%20Rhys%2C%20I%20would%20like%20to%20book%20a%20Full%20Valet%20Package%20car%20model%20%3A%20',
  },
  {
    id: 'deep-clean',
    title: 'Deep Clean Package',
    subtitle: 'For the car that needs rescuing — not just washing',
    benefit: 'Pet hair. Stains. Years of daily life. We remove all of it — leaving your car in a state that makes people ask if you just bought it.',
    description: [
      'All dashboard surfaces cleaned',
      'Interior deep vacuum',
      'Leather conditioner treatment',
      'Plastic dressing',
      'Trim conditioner',
      'Tyre dressing',
      'Upholstery cleaned (wet vac)',
      'Safe wash (3-bucket method)',
      'Door shuts cleaned',
      'Wheel arches deep clean',
      'Interior steam cleaned',
      'Pet hair & stains removed',
      'Interior air blast — all creases',
      'Interior & exterior glass cleaned',
      'Exterior decontamination / tar removal',
      'Interior air freshener',
    ],
    price: 'From £120',
    duration: '4–5 hrs',
    image: '/724453567_1741795673842657_7212829807354336478_n.jpg',
    bookingUrl: 'https://wa.me/447393682365?text=Hi%20Rhys%2C%20I%20would%20like%20to%20book%20a%20Deep%20Clean%20Package%20car%20model%20%3A%20',
  },
];

export const ADDON_PACKAGES = [
  {
    id: 'winter-protection',
    title: 'Winter Protection Package',
    badge: 'Seasonal Protection',
    subtitle: 'Cold weather defense against road salt, grit & harsh moisture',
    benefit: 'Shield your paint, wheels, and glass against winter road grime with heavy-duty 6-month sealants and water repellent coatings.',
    price: '£60',
    duration: '2–2.5 hrs',
    image: '/793802536_1695259291991167_7413069740708566362_n.jpg',
    description: [
      'Snow foam, pre-wash & rinse',
      '3-bucket safe wash method',
      'Arches blasted and brushed out',
      'Full paint decontamination',
      'Tar removed safely',
      'Interior door shuts cleaned',
      'Rain repellent applied to windscreen',
      'Wheel sealant applied',
      '6 months paint sealant applied',
      'Finished off with a fresh interior scent',
    ],
    bookingUrl: 'https://wa.me/447393682365?text=Hi%20Rhys%2C%20I%20would%20like%20to%20book%20the%20Winter%20Protection%20Package%20%28%C2%A360%29.%20Vehicle%20model%3A%20',
  },
  {
    id: 'new-car-protection',
    title: 'New Car Protection Package',
    badge: '2-Year Ceramic Seal',
    subtitle: 'Showroom preservation and long-lasting ceramic protection',
    benefit: 'Lock in that pristine factory finish from day one with dedicated surface decontamination and genuine 2-year ceramic coating on paint & glass.',
    price: 'From £100',
    duration: '3–4 hrs',
    image: '/792999549_1096716916146576_7755589812413831663_n.jpg',
    pureWaterNote: 'We arrive with our own 100% spotless pure water, so no tap is needed — all we ask for is a standard 13A socket and a place to park.',
    description: [
      'Pre-wash & safe 3-bucket contact wash',
      'Full decontamination & tar removal',
      'Full interior vacuum',
      'Fabric sealed or leather cleaned & treated',
      'Wheels cleaned, tyres dressed & glass cleaned',
      '2 year ceramic coating on paint & glass',
    ],
    bookingUrl: 'https://wa.me/447393682365?text=Hi%20Rhys%2C%20I%20would%20like%20to%20book%20the%20New%20Car%20Protection%20Package%20%28From%20%C2%A3100%29.%20Vehicle%20model%3A%20',
  },
];

export const ADDON_EXTRAS = [
  {
    id: 'glass-ceramic-coating',
    category: 'RAIN GUARD',
    categoryColor: '#38BDF8',
    title: '2 Year Glass Ceramic Coating',
    description: 'An ultra-slick hydrophobic seal on the glass that throws rainwater off the windows at speed — clearer vision in bad weather, and far less wiper work.',
    price: 'From £40',
    priceColor: '#38BDF8',
    image: '/719890908_2222286848526617_3057517277440017740_n.jpg',
    bookingUrl: 'https://wa.me/447393682365?text=Hi%20Rhys%2C%20I%20would%20like%20to%20add%20the%202%20Year%20Glass%20Ceramic%20Coating%20%28From%20%C2%A340%29%20to%20my%20valet.%20Vehicle%20model%3A%20',
  },
  {
    id: 'convertible-roof-clean',
    category: 'FABRIC CARE',
    categoryColor: '#EF4444',
    title: 'Convertible Roof Deep Clean',
    description: 'A fabric roof holds dirt and green growth in a way paint never does. The weave is cleaned right through, lifted of staining, and left able to shed water again instead of soaking it up.',
    price: '£40',
    priceColor: '#EF4444',
    image: '/roof (2).jpg',
    bookingUrl: 'https://wa.me/447393682365?text=Hi%20Rhys%2C%20I%20would%20like%20to%20add%20the%20Convertible%20Roof%20Deep%20Clean%20%28%C2%A340%29%20to%20my%20valet.%20Vehicle%20model%3A%20',
  },
  {
    id: 'engine-bay-clean',
    category: 'UNDER THE BONNET',
    categoryColor: '#38BDF8',
    title: 'Engine Bay Cleaned & Dressed',
    description: 'Years of road dust and oil film taken off the bay, then every plastic and hose dressed back to a clean satin finish. The detail nobody expects and every buyer notices when the bonnet goes up.',
    price: '£50',
    priceColor: '#FFFFFF',
    image: '/engine.jpg',
    bookingUrl: 'https://wa.me/447393682365?text=Hi%20Rhys%2C%20I%20would%20like%20to%20add%20the%20Engine%20Bay%20Cleaned%20%26%20Dressed%20%28%C2%A350%29%20to%20my%20valet.%20Vehicle%20model%3A%20',
  },
];

export const TESTIMONIALS = [
  {
    name: 'James R.',
    car: 'Porsche 911 Owner',
    text: 'Absolutely fantastic full valet by Rhys at RD Valeting today. The car looks better than when I bought it — spotless inside and out with amazing attention to detail. Friendly, professional service and completed to a really high standard. Would highly recommend RD Valeting to anyone wanting their car looking like new again. Thank you Rhys!',
    avatar: '/james_r_avatar.png',
    stars: 5,
  },
  {
    name: 'Amanda S.',
    car: 'Audi A4 Owner',
    text: 'Excellent valet done on my car by Rhys. Looks brand new and smells amazing! A highly thorough and professional job. Definitely recommend to anyone who values their vehicle.',
    avatar: '/amanda_s_avatar.png',
    stars: 5,
  },
  {
    name: 'Margaret & John',
    car: 'Mercedes E-Class Owner',
    text: 'Rhys was great, very careful and left our pride and joy looking like new. Prompt arrival, polite demeanor and astonishing standard of work. Superb mobile valeting service.',
    avatar: '/margaret_john_avatar.png',
    stars: 5,
  },
  {
    name: 'Paul B.',
    car: 'Porsche Boxster S Owner',
    text: 'Rees did a brilliant job on my treasured 2010 Gen 2 Boxster S and even unjammed my outside tap!! I would have no hesitation in recommending him... Great job... Great price... Great service and looking forward to next valet!',
    avatar: '/tom_d_avatar.png',
    stars: 5,
  },
  {
    name: 'Sarah M.',
    car: 'BMW 1-Series Owner',
    text: 'Rhys came right to our driveway and made our car look showroom-ready in a few hours. The paint has a mirror reflection and the interior feels so fresh. 10/10 service!',
    avatar: '/sarah_m_avatar.png',
    stars: 5,
  },
];

export const ACCREDITATIONS = [
  { name: '100% Satisfaction Guaranteed', logo: '' },
  { name: 'Fully Insured & Professional', logo: '' },
  { name: 'Mobile — We Come To You', logo: '' },
];

export const COMPANY_DETAILS = {
  name: 'RD Valeting',
  tagline: 'Mobile Valeting You Can Trust · Swindon & Wiltshire',
  address: 'Serving Swindon, Wiltshire & Surrounding Areas',
  travelRange: 'Mobile valeting — we come directly to your driveway or workplace',
  phone: '07393 682 365',
  phoneRaw: '07393682365',
  email: 'bookings@rdvaleting.co.uk',
  hours: 'Mon – Sun  8:00 AM – 7:00 PM',
  bookingUrl: 'https://wa.me/447393682365?text=Hello%20Rhys%2C%20I%20would%20like%20to%20book%20a%20valeting%20appointment%20with%20RD%20Valeting.',
  whatsapp: 'https://wa.me/447393682365',
  instagram: 'https://www.instagram.com/rd_valeting_/',
  facebook: 'https://www.facebook.com/profile.php?id=61583261669534#',
  tiktok: 'https://tiktok.com',
  googleReview: 'https://www.google.com/search?sa=X&sca_esv=4f62c56bf724f716&hl=en-GB&biw=1536&bih=730&sxsrf=ANbL-n41syGit6F0ezVWoJL2T3RDA_LmYw:1781779439450&kgmid=/g/11yw13dtwq&q=RD+Valeting&shem=epsd1,ltae,rimspwouoe&shndl=30&source=sh/x/loc/uni/m1/1&kgs=e9b22e0d3fa3f43d&utm_source=epsd1,ltae,rimspwouoe,sh/x/loc/uni/m1/1#lrd=0x487143683438d6f9:0x831248bbecc5480,3,,,,',
  websiteUrl: 'https://rdvaleting.co.uk/',
};

export const GALLERY_MEDIA = [
  {
    id: 1,
    type: 'image',
    title: 'Porsche 911 — Full Valet, Swindon',
    desc: 'Complete full valet and machine polish for a Swindon-based Porsche 911 — deep gloss, zero swirls, showroom-ready finish.',
    url: '/719890908_2222286848526617_3057517277440017740_n.jpg',
    span: 'md:col-span-2 md:row-span-2 sm:col-span-2 sm:row-span-2',
  },
  {
    id: 2,
    type: 'image',
    title: 'Porsche Interior Detail — Wiltshire',
    desc: 'Meticulous leather conditioning and dashboard restoration carried out at the customer\'s home in Wiltshire.',
    url: '/720736240_1740150606990218_6668730905296473434_n.jpg',
    span: 'md:col-span-1 md:row-span-3 sm:col-span-2 sm:row-span-2',
  },
  {
    id: 3,
    type: 'image',
    title: 'Paint Enhancement — Mobile Detailing',
    desc: 'Mirror-finish gloss achieved through machine polishing — a hallmark of RD Valeting\'s professional mobile detailing service.',
    url: '/722131074_3250354271804383_1989022274874112064_n.jpg',
    span: 'md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2',
  },
  {
    id: 4,
    type: 'image',
    title: 'Alloy Wheel Decontamination — Swindon',
    desc: 'pH-safe iron fallout removal, barrel brush clean, and caliper detailing — part of every Full Valet & Detailing package in Swindon.',
    url: '/722468637_1408418911098456_1142949210350927502_n.jpg',
    span: 'md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2',
  },
  {
    id: 5,
    type: 'image',
    title: 'Snow Foam Pre-Wash — Safe Wash Method',
    desc: 'High-density snow foam pre-soak safely lifts road grime before any contact with the paint — preventing swirls and scratches.',
    url: '/723830628_27152605947682802_3120737853125552335_n.jpg',
    span: 'md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2',
  },
  {
    id: 6,
    type: 'image',
    title: 'RD Valeting Mobile Unit — Swindon & Wiltshire',
    desc: 'Fully self-contained professional mobile valeting unit. We arrive at your driveway or workplace across Swindon, Wiltshire, and surrounding areas.',
    url: '/723456333_1027111233340868_6744532048742945277_n.jpg',
    span: 'md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2',
  },
  {
    id: 7,
    type: 'image',
    title: 'Interior Deep Clean & Hot Extraction',
    desc: 'Seats, carpets, and boot mats treated with professional hot water extraction — eliminating stains, odours, and embedded dirt.',
    url: '/721348016_3050409318485692_5175913260259492992_n.jpg',
    span: 'md:col-span-1 md:row-span-3 sm:col-span-1 sm:row-span-2',
  },
  {
    id: 8,
    type: 'image',
    title: 'BMW M-Sport — Full Detail, Wiltshire',
    desc: 'Full valet transformation on a BMW M-Sport: streak-free glass, dressed tyres, and a showroom-grade finish delivered to the customer\'s driveway.',
    url: '/722908490_1513785427083168_6885942169468714202_n.jpg',
    span: 'md:col-span-2 md:row-span-2 sm:col-span-1 sm:row-span-2',
  },
];

export const FAQ_DATA = [
  {
    question: 'Do I need to provide water or power?',
    answer: 'RD Valeting carries its own 100% pure spotless water — no tap required. We do require access to a standard 13A plug socket for our equipment, and we bring an extension lead so you do not need to worry about reach. If you are at a workplace, please confirm a socket is available before booking.',
  },
  {
    question: 'What is pure water and why does it matter?',
    answer: 'Pure water has had the dissolved minerals stripped out of it. Ordinary tap water leaves those minerals behind as it dries — the white spots you see on glass and dark paint. Our purified water dries completely clean, so the finish holds rather than needing chasing with a towel. The result is a sharper, longer-lasting shine with zero water marks.',
  },
  {
    question: 'Are you insured?',
    answer: 'Yes — RD Valeting is fully insured, so your vehicle is covered for the entire visit. If anything were ever not right, it gets dealt with properly rather than argued about. Your car is in safe hands from the moment we arrive to the moment we leave.',
  },
  {
    question: 'What is the difference between a Full Valet and a Deep Clean?',
    answer: 'A Full Valet (£70) is a comprehensive reset for a car in normal everyday condition — snow foam, safe three-bucket hand wash, interior refresh, trim dressed, and a spray sealant on the paint for four months of protection. A Deep Clean (£120) goes further, for the car that needs rescuing rather than maintaining: wet extraction machine shampoo through seats and carpets, pet hair and stains lifted, iron fallout and tar chemically purged from the paintwork, and a full steam interior clean. If the car is dusty, take the Full Valet. If it has been lived in, take the Deep Clean.',
  },
  {
    question: 'How often should I book a valet?',
    answer: 'For most drivers, start with a Full Valet and then move onto the Maintenance Plan every 2–4 weeks. The plan is built to hold a finish rather than create one — keeping your protection layer topped up and your car consistently presentable. One-off Deep Cleans are ideal for pre-sale preparation, seasonal resets, or after heavy use.',
  },
  {
    question: 'Is ceramic coating worth it?',
    answer: 'If you want the finish to keep itself clean, yes. A ceramic layer is hydrophobic, chemically resistant, and UV-stable — water sheets off and road grime struggles to grip. Paint coating comes as part of our New Car Protection package (from £100), which includes the full valet and glass coating. The glass coating on its own (from £40) does the same job on the windows — rain flies off at speed and your wipers barely need to work.',
  },
  {
    question: 'What if it rains on the day?',
    answer: 'Light rain does not affect most of our work, particularly interior packages. For exterior treatments that require a dry surface — such as sealant application — we will let you know in advance and reschedule at no charge to you if needed. We work around your life, not the other way around.',
  },
  {
    question: 'Which areas do you cover?',
    answer: 'Swindon, Chippenham, Royal Wootton Bassett, Highworth, Marlborough, Cirencester and the wider Wiltshire area. If you are just outside, send a postcode and we will confirm straight away — we regularly travel further for the right job.',
  },
  {
    question: 'How do I book?',
    answer: 'Message on WhatsApp, call 07393 682365, or fill in the contact form with your vehicle details and what it needs. We work around you — evenings and weekends included — so get in touch and we will find a slot that fits.',
  },
];
